apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
spec:
  containers:
    - name: php-fpm-container
      image: php:7.2-fpm-alpine
      imagePullPolicy: IfNotPresent
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        # FIX: Mount shared volume at same path as nginx
        - name: shared-files
          mountPath: /var/www/html      # This path was initially /usr/nginx/...
        - name: kube-api-access-qm86m
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true

    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: Always
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf

  volumes:
    - name: shared-files
      emptyDir: {}

    - name: nginx-config-volume
      configMap:
        name: nginx-config
