apiVersion: v1
kind: Pod
metadata:
    name: volume-share-nautilus
spec:
    containers: 
        - name: volume-container-nautilus-1
          image: fedora:latest
          command: ["sleep", "infinity"]
          volumeMounts:
              - name: volume-share
                mountPath: /tmp/blog

        - name: volume-container-nautilus-2
          image: fedora:latest
          command: ["sleep", "infinity"]
          volumeMounts:
              - name: volume-share
                mountPath: /tmp/demo
    volumes:
        - name: volume-share
          emptyDir: {}