apiVersion: v1
kind: Pod
metadata:
   name: pod-devops
   labels:
      app: nginx
spec:
   containers:
      - name: container-devops
        image: nginx:latest
        ports:
           - containerPort: 80
        volumeMounts:
           - mountPath: /usr/share/nginx/html
             name: devops-vol
   volumes:
      - name: devops-vol
        persistentVolumeClaim:
           claimName: pvc-devops